/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tagClient

type ModelTagCreateReqTagInfo struct {
	Color string `json:"color"`
	DomainId string `json:"domain_id,omitempty"`
	Key string `json:"key"`
	ProjectId string `json:"project_id,omitempty"`
	Value string `json:"value,omitempty"`
	Visibility string `json:"visibility"`
}
