/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TagClient

type ModelResourceGetBoundTagReqResData struct {
	Id string `json:"id"`
	Name string `json:"name"`
	ProjectId string `json:"project_id"`
	ResourceType string `json:"resource_type"`
}
