/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tagClient

type ModelTagDeleteReqData struct {
	Color string `json:"color"`
	DomainId string `json:"domain_id"`
	Id string `json:"id"`
	ProjectId string `json:"project_id"`
	Tag string `json:"tag"`
}
