/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TagClient

type ModelTrtsGetRes struct {
	// 所属模块
	Belong string `json:"belong,omitempty"`
	Category string `json:"category,omitempty"`
	// 创建时间
	CreateTime string `json:"create_time,omitempty"`
	Description string `json:"description,omitempty"`
	// 跳转链接
	Link string `json:"link,omitempty"`
	Multilanguage *ModelTrtsGetMultiLanguage `json:"multilanguage,omitempty"`
	// 资源类型
	Name string `json:"name,omitempty"`
}
