/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TagClient

type ModelResourceGetBoundTagsData struct {
	Color string `json:"color,omitempty"`
	Id string `json:"id,omitempty"`
	Tag string `json:"tag,omitempty"`
}
