/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tagClient

type ModelResourceSearchResMultiLanguage struct {
	BelongEn string `json:"belong_en,omitempty"`
	BelongZhCn string `json:"belong_zh_cn,omitempty"`
	NameEn string `json:"name_en,omitempty"`
	NameZhCn string `json:"name_zh_cn,omitempty"`
}
