/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tagClient

type ModelResourceSearchReq struct {
	Domain string `json:"domain,omitempty"`
	Project string `json:"project"`
	ResourceType []string `json:"resource_type"`
	Tags []ModelResourceSearchReqTagData `json:"tags,omitempty"`
}
