/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TagClient

type ResponseAuthErrRes struct {
	// 错误代码
	Code string `json:"code,omitempty"`
	// 提示信息
	Message string `json:"message,omitempty"`
}
