/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TagClient

type ModelTrtsGetMultiLanguage struct {
	BelongEn string `json:"belong_en,omitempty"`
	// 中文所属
	BelongZhCn string `json:"belong_zh_cn,omitempty"`
	CategoryEn string `json:"category_en,omitempty"`
	CategoryZhCn string `json:"category_zh_cn,omitempty"`
	DescriptionEn string `json:"description_en,omitempty"`
	DescriptionZhCn string `json:"description_zh_cn,omitempty"`
	// 英文名字
	NameEn string `json:"name_en,omitempty"`
	// 中文名字
	NameZhCn string `json:"name_zh_cn,omitempty"`
}
