/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tagClient

type ModelTagCreateReq struct {
	Tag *ModelTagCreateReqTagInfo `json:"tag"`
}
