/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TagClient

type ModelDepartmentGetProjectRes struct {
	DomainId string `json:"domain_id,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	ParentId string `json:"parent_id,omitempty"`
}
