/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TagClient

type ModelTagDeleteTagsErrRes struct {
	Code string `json:"code,omitempty"`
	Data interface{} `json:"data,omitempty"`
	Message string `json:"message,omitempty"`
}
