/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tagClient

type ModelResourceSearchRes struct {
	CustomTags []ModelResourceSearchResTagData `json:"custom_tags,omitempty"`
	DomainId string `json:"domain_id,omitempty"`
	DomainName string `json:"domain_name,omitempty"`
	Id string `json:"id,omitempty"`
	Link string `json:"link,omitempty"`
	MultiLanguage *ModelResourceSearchResMultiLanguage `json:"multiLanguage,omitempty"`
	Name string `json:"name,omitempty"`
	ProjectId string `json:"project_id,omitempty"`
	ProjectName string `json:"project_name,omitempty"`
	ResourceType string `json:"resource_type,omitempty"`
}
