/*
 * tag-api OpenAPI Doc
 *
 * tag-api OpenAPI doc
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TagClient

type ModelResourceBoundOrUnboundTagErrList struct {
	ErrorReason string `json:"error_reason,omitempty"`
	ErrorResource string `json:"error_resource,omitempty"`
	ErrorResourceType string `json:"error_resource_type,omitempty"`
	ErrorTags string `json:"error_tags,omitempty"`
}
